spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5455}/banking_db
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
springdoc:
  api-docs:
    path: /api-docs
server:
  servlet:
    context-path: /banking-api/v1
