spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5455/banking_db
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
springdoc:
  api-docs:
    path: /api-docs
server:
  servlet:
    context-path: /banking-api/v1
